export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_PENDING = 'SIGN_IN_PENDING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const GOOGLE_URL = 'GOOGLE_URL';
export const GOOGLE_URL_PENDING = 'GOOGLE_URL_PENDING';
export const GOOGLE_URL_SUCCESS = 'GOOGLE_URL_SUCCESS';
export const GOOGLE_URL_FAILED = 'GOOGLE_URL_FAILED';

export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
